---
clone_depth: 10
install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - bundle install
build_script:
  - rake -rdevkit compile
test_script:
  - rake test
deploy: off
environment:
  matrix:
    - ruby_version: "24"
    - ruby_version: "25"
