name: windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ mingw, mswin, 2.7, 2.6, 2.5, 2.4 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: MSP-Greg/actions-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          base: update
      - name: Install dependencies
        run: bundle install
      - name: Run test
        if: matrix.ruby != 'mswin'
        run: rake
      - name: Run test
        if: matrix.ruby == 'mswin'
        shell: cmd
        run: |
          call "%VCVARS%"
          rake
